import React from 'react';

interface LivePreviewProps {
    templateId: string;
    resumeData: any; // The JSON generated by AI
}

const LivePreview: React.FC<LivePreviewProps> = ({ templateId, resumeData }) => {

    if (!resumeData) {
        return (
            <div className="flex flex-col items-center gap-4 text-gray-500">
                <p>Generating layout...</p>
                <div className="animate-spin h-8 w-8 border-4 border-purple-500 border-t-transparent rounded-full"></div>
            </div>
        );
    }

    const { personalInfo, professionalSummary, skills, softSkills, experience, education, projects, certifications } = resumeData;

    // Helper to safely escape XML/HTML characters for SVG injection
    const escapeXml = (unsafe: string) => {
        if (!unsafe) return "";
        return unsafe.toString().replace(/[<>&'"]/g, (c) => {
            switch (c) {
                case '<': return '&lt;';
                case '>': return '&gt;';
                case '&': return '&amp;';
                case '\'': return '&apos;';
                case '"': return '&quot;';
                default: return c;
            }
        });
    };

    const renderTemplate1 = () => (
        <svg width="794" height="1123" viewBox="0 0 794 1123" xmlns="http://www.w3.org/2000/svg" fontFamily="Arial, Helvetica, sans-serif">
            <rect width="794" height="1123" fill="#ffffff"/>
            <rect width="794" height="105" fill="#1e2235"/>
            <rect y="105" width="794" height="5" fill="#2ecfcf"/>
            
            {/* Header */}
            <text x="397" y="48" textAnchor="middle" fill="#ffffff" fontSize="28" fontWeight="bold" letterSpacing="4" fontFamily="Arial Black, Arial, sans-serif">
                {escapeXml(personalInfo?.name?.toUpperCase() || '')}
            </text>
            <text x="397" y="68" textAnchor="middle" fill="#2ecfcf" fontSize="10" letterSpacing="2">
                {escapeXml(personalInfo?.headline?.toUpperCase() || '')}
            </text>
            <text x="397" y="90" textAnchor="middle" fill="#9aa0b8" fontSize="9">
                {[
                    escapeXml(personalInfo?.location), 
                    escapeXml(personalInfo?.email), 
                    escapeXml(personalInfo?.phoneNumber), 
                    escapeXml(personalInfo?.linkedin),
                    escapeXml(personalInfo?.github)
                ].filter(Boolean).join('  •  ')}
            </text>

            <foreignObject x="40" y="130" width="714" height="950">
                <div xmlns="http://www.w3.org/1999/xhtml" style={{ fontSize: '12px', color: '#444', fontFamily: 'Arial, sans-serif', lineHeight: '1.5' }}>
                    
                    {/* Summary */}
                    {professionalSummary && (
                        <div style={{ marginBottom: '20px' }}>
                            <div style={{ color: '#1e2235', fontSize: '10.5px', fontWeight: 'bold', letterSpacing: '1.5px', borderBottom: '1.5px solid #2ecfcf', paddingBottom: '2px', marginBottom: '8px' }}>
                                PROFESSIONAL SUMMARY
                            </div>
                            <div>{escapeXml(professionalSummary)}</div>
                        </div>
                    )}

                    {/* Experience */}
                    {experience && experience.length > 0 && (
                        <div style={{ marginBottom: '20px' }}>
                            <div style={{ color: '#1e2235', fontSize: '10.5px', fontWeight: 'bold', letterSpacing: '1.5px', borderBottom: '1.5px solid #2ecfcf', paddingBottom: '2px', marginBottom: '8px' }}>
                                WORK EXPERIENCE
                            </div>
                            {experience.map((exp: any, idx: number) => (
                                <div key={idx} style={{ marginBottom: '15px' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '13px', color: '#1e2235' }}>
                                        <span>{escapeXml(exp.company)} {exp.location ? `| ${escapeXml(exp.location)}` : ''}</span>
                                        <span style={{ color: '#888', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(exp.startDate)} – {escapeXml(exp.endDate)}</span>
                                    </div>
                                    <div style={{ color: '#2ecfcf', fontSize: '12px', fontStyle: 'italic', marginBottom: '5px' }}>{escapeXml(exp.jobTitle)}</div>
                                    {exp.bullets && exp.bullets.length > 0 && (
                                        <ul style={{ margin: 0, paddingLeft: '15px', color: '#555', fontSize: '12px' }}>
                                            {exp.bullets.map((bullet: string, bIdx: number) => (
                                                <li key={bIdx} style={{ marginBottom: '3px' }}>{escapeXml(bullet)}</li>
                                            ))}
                                        </ul>
                                    )}
                                </div>
                            ))}
                        </div>
                    )}

                    {/* Projects */}
                    {projects && projects.length > 0 && (
                        <div style={{ marginBottom: '20px' }}>
                            <div style={{ color: '#1e2235', fontSize: '10.5px', fontWeight: 'bold', letterSpacing: '1.5px', borderBottom: '1.5px solid #2ecfcf', paddingBottom: '2px', marginBottom: '8px' }}>
                                KEY PROJECTS
                            </div>
                            {projects.map((proj: any, idx: number) => (
                                <div key={idx} style={{ marginBottom: '15px' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '13px', color: '#1e2235' }}>
                                        <span>{escapeXml(proj.name)}</span>
                                        <span style={{ color: '#888', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(proj.startDate)} – {escapeXml(proj.endDate)}</span>
                                    </div>
                                    {proj.role && <div style={{ color: '#2ecfcf', fontSize: '12px', fontStyle: 'italic', marginBottom: '5px' }}>{escapeXml(proj.role)}</div>}
                                    {proj.bullets && proj.bullets.length > 0 && (
                                        <ul style={{ margin: 0, paddingLeft: '15px', color: '#555', fontSize: '12px' }}>
                                            {proj.bullets.map((bullet: string, bIdx: number) => (
                                                <li key={bIdx} style={{ marginBottom: '3px' }}>{escapeXml(bullet)}</li>
                                            ))}
                                        </ul>
                                    )}
                                </div>
                            ))}
                        </div>
                    )}

                    {/* Education */}
                    {education && education.length > 0 && (
                        <div style={{ marginBottom: '20px' }}>
                            <div style={{ color: '#1e2235', fontSize: '10.5px', fontWeight: 'bold', letterSpacing: '1.5px', borderBottom: '1.5px solid #2ecfcf', paddingBottom: '2px', marginBottom: '8px' }}>
                                EDUCATION
                            </div>
                            {education.map((edu: any, idx: number) => (
                                <div key={idx} style={{ marginBottom: '10px' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '13px', color: '#1e2235' }}>
                                        <span>{escapeXml(edu.degree)}</span>
                                        <span style={{ color: '#888', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(edu.startDate)} – {escapeXml(edu.endDate)}</span>
                                    </div>
                                    <div style={{ color: '#666', fontSize: '12px' }}>{escapeXml(edu.institution)}{edu.location ? `, ${escapeXml(edu.location)}` : ''}</div>
                                    {edu.highlights && <div style={{ color: '#888', fontSize: '11px', marginTop: '2px' }}>{escapeXml(edu.highlights)}</div>}
                                </div>
                            ))}
                        </div>
                    )}
                    
                    {/* Skills & Certifications Row */}
                    <div style={{ display: 'flex', gap: '40px' }}>
                        {skills && skills.length > 0 && (
                            <div style={{ flex: 1 }}>
                                <div style={{ color: '#1e2235', fontSize: '10.5px', fontWeight: 'bold', letterSpacing: '1.5px', borderBottom: '1.5px solid #2ecfcf', paddingBottom: '2px', marginBottom: '8px' }}>
                                    HARD SKILLS
                                </div>
                                <ul style={{ margin: 0, paddingLeft: '15px', color: '#555', fontSize: '12px' }}>
                                    {skills.map((skill: string, idx: number) => (
                                        <li key={idx} style={{ marginBottom: '3px' }}>{escapeXml(skill)}</li>
                                    ))}
                                </ul>
                            </div>
                        )}
                        
                        {softSkills && softSkills.length > 0 && (
                            <div style={{ flex: 1 }}>
                                <div style={{ color: '#1e2235', fontSize: '10.5px', fontWeight: 'bold', letterSpacing: '1.5px', borderBottom: '1.5px solid #2ecfcf', paddingBottom: '2px', marginBottom: '8px' }}>
                                    SOFT SKILLS
                                </div>
                                <ul style={{ margin: 0, paddingLeft: '15px', color: '#555', fontSize: '12px' }}>
                                    {softSkills.map((skill: string, idx: number) => (
                                        <li key={idx} style={{ marginBottom: '3px' }}>{escapeXml(skill)}</li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {certifications && certifications.length > 0 && (
                            <div style={{ flex: 1 }}>
                                <div style={{ color: '#1e2235', fontSize: '10.5px', fontWeight: 'bold', letterSpacing: '1.5px', borderBottom: '1.5px solid #2ecfcf', paddingBottom: '2px', marginBottom: '8px' }}>
                                    CERTIFICATIONS
                                </div>
                                <ul style={{ margin: 0, paddingLeft: '15px', color: '#555', fontSize: '12px' }}>
                                    {certifications.map((cert: string, idx: number) => (
                                        <li key={idx} style={{ marginBottom: '3px' }}>{escapeXml(cert)}</li>
                                    ))}
                                </ul>
                            </div>
                        )}
                    </div>

                </div>
            </foreignObject>
        </svg>
    );

    const renderTemplate2 = () => (
        <svg width="794" height="1123" viewBox="0 0 794 1123" xmlns="http://www.w3.org/2000/svg" fontFamily="Arial, Helvetica, sans-serif">
            <rect width="794" height="1123" fill="#ffffff"/>
            <rect width="240" height="1123" fill="#1e1f3b"/>
            <rect width="240" height="6" fill="#e8723f"/>
            <rect x="240" width="3" height="1123" fill="#e8723f"/>

            {/* Sidebar Content */}
            <text x="120" y="140" textAnchor="middle" fill="#ffffff" fontSize="18" fontWeight="bold" fontFamily="Arial Black, Arial, sans-serif">
                {escapeXml(personalInfo?.name?.toUpperCase() || '')}
            </text>
            <text x="120" y="160" textAnchor="middle" fill="#9a9bbf" fontSize="10" letterSpacing="1">
                {escapeXml((personalInfo?.headline || '').substring(0, 35).toUpperCase())}
            </text>
            
            <line x1="20" y1="180" x2="220" y2="180" stroke="#3a3c66" strokeWidth="1"/>
            
            <foreignObject x="20" y="200" width="200" height="100">
                <div xmlns="http://www.w3.org/1999/xhtml" style={{ color: '#c0c2e0', fontSize: '10px', textAlign: 'center', lineHeight: '1.8' }}>
                    {personalInfo?.phoneNumber && <div>{escapeXml(personalInfo.phoneNumber)}</div>}
                    {personalInfo?.email && <div>{escapeXml(personalInfo.email)}</div>}
                    {personalInfo?.linkedin && <div>{escapeXml(personalInfo.linkedin.replace(/^https?:\/\/(www\.)?/, ''))}</div>}
                    {personalInfo?.github && <div>{escapeXml(personalInfo.github.replace(/^https?:\/\/(www\.)?/, ''))}</div>}
                    {personalInfo?.location && <div>{escapeXml(personalInfo.location)}</div>}
                </div>
            </foreignObject>

            <line x1="20" y1="310" x2="220" y2="310" stroke="#3a3c66" strokeWidth="1"/>
            
            {skills && skills.length > 0 && (
                <>
                    <text x="20" y="340" fill="#ffffff" fontSize="12" fontWeight="bold" letterSpacing="1">HARD SKILLS</text>
                    <foreignObject x="20" y="350" width="200" height="150">
                        <div xmlns="http://www.w3.org/1999/xhtml" style={{ fontFamily: 'Arial, sans-serif', color: '#c8c9e5', fontSize: '11px' }}>
                            {skills.map((skill: string, idx: number) => (
                                <div key={idx} style={{ marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                                    <div style={{ width: '5px', height: '5px', borderRadius: '50%', backgroundColor: '#e8723f' }}></div>
                                    <span>{escapeXml(skill)}</span>
                                </div>
                            ))}
                        </div>
                    </foreignObject>
                </>
            )}

            {softSkills && softSkills.length > 0 && (
                <>
                    <text x="20" y="520" fill="#ffffff" fontSize="12" fontWeight="bold" letterSpacing="1">SOFT SKILLS</text>
                    <foreignObject x="20" y="530" width="200" height="150">
                        <div xmlns="http://www.w3.org/1999/xhtml" style={{ fontFamily: 'Arial, sans-serif', color: '#c8c9e5', fontSize: '11px' }}>
                            {softSkills.map((skill: string, idx: number) => (
                                <div key={idx} style={{ marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                                    <div style={{ width: '5px', height: '5px', borderRadius: '50%', backgroundColor: '#e8723f' }}></div>
                                    <span>{escapeXml(skill)}</span>
                                </div>
                            ))}
                        </div>
                    </foreignObject>
                </>
            )}

            {/* Main Content */}
            <foreignObject x="260" y="50" width="494" height="1000">
                <div xmlns="http://www.w3.org/1999/xhtml" style={{ fontFamily: 'Arial, sans-serif' }}>
                    <div style={{ fontSize: '26px', fontWeight: 'bold', color: '#1e1f3b', textTransform: 'uppercase', fontFamily: 'Arial Black, Arial, sans-serif' }}>
                        {escapeXml(personalInfo?.name || '')}
                    </div>
                    <div style={{ color: '#e8723f', fontSize: '12px', marginTop: '4px', marginBottom: '15px' }}>
                        {escapeXml(personalInfo?.headline || '')}
                    </div>
                    <div style={{ height: '1px', backgroundColor: '#e8e8e8', marginBottom: '20px' }}></div>

                    {professionalSummary && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ color: '#1e1f3b', fontSize: '12px', fontWeight: 'bold', letterSpacing: '1px', borderBottom: '2px solid #e8723f', paddingBottom: '4px', marginBottom: '10px' }}>
                                SUMMARY
                            </div>
                            <div style={{ fontSize: '12px', color: '#555', lineHeight: '1.5' }}>
                                {escapeXml(professionalSummary)}
                            </div>
                        </div>
                    )}

                    {experience && experience.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ color: '#1e1f3b', fontSize: '12px', fontWeight: 'bold', letterSpacing: '1px', borderBottom: '2px solid #e8723f', paddingBottom: '4px', marginBottom: '15px' }}>
                                EXPERIENCE
                            </div>
                            <div style={{ borderLeft: '1.5px solid #e8e8e8', paddingLeft: '15px', position: 'relative' }}>
                                {experience.map((exp: any, idx: number) => (
                                    <div key={idx} style={{ marginBottom: '20px', position: 'relative' }}>
                                        <div style={{ position: 'absolute', left: '-20px', top: '4px', width: '10px', height: '10px', borderRadius: '50%', backgroundColor: '#e8723f' }}></div>
                                        <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '14px', color: '#1e1f3b' }}>
                                            <span>{escapeXml(exp.jobTitle)}</span>
                                            <span style={{ color: '#999', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(exp.startDate)} – {escapeXml(exp.endDate)}</span>
                                        </div>
                                        <div style={{ color: '#e8723f', fontSize: '12px', marginBottom: '5px' }}>{escapeXml(exp.company)}</div>
                                        {exp.bullets && exp.bullets.length > 0 && (
                                            <ul style={{ margin: 0, paddingLeft: '15px', color: '#666', fontSize: '12px', lineHeight: '1.4' }}>
                                                {exp.bullets.map((bullet: string, bIdx: number) => (
                                                    <li key={bIdx} style={{ marginBottom: '4px' }}>{escapeXml(bullet)}</li>
                                                ))}
                                            </ul>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {projects && projects.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ color: '#1e1f3b', fontSize: '12px', fontWeight: 'bold', letterSpacing: '1px', borderBottom: '2px solid #e8723f', paddingBottom: '4px', marginBottom: '15px' }}>
                                PROJECTS
                            </div>
                            <div style={{ borderLeft: '1.5px solid #e8e8e8', paddingLeft: '15px', position: 'relative' }}>
                                {projects.map((proj: any, idx: number) => (
                                    <div key={idx} style={{ marginBottom: '20px', position: 'relative' }}>
                                        <div style={{ position: 'absolute', left: '-20px', top: '4px', width: '10px', height: '10px', borderRadius: '50%', backgroundColor: '#e8723f' }}></div>
                                        <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '14px', color: '#1e1f3b' }}>
                                            <span>{escapeXml(proj.name)}</span>
                                            <span style={{ color: '#999', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(proj.startDate)} – {escapeXml(proj.endDate)}</span>
                                        </div>
                                        {proj.role && <div style={{ color: '#e8723f', fontSize: '12px', marginBottom: '5px' }}>{escapeXml(proj.role)}</div>}
                                        {proj.bullets && proj.bullets.length > 0 && (
                                            <ul style={{ margin: 0, paddingLeft: '15px', color: '#666', fontSize: '12px', lineHeight: '1.4' }}>
                                                {proj.bullets.map((bullet: string, bIdx: number) => (
                                                    <li key={bIdx} style={{ marginBottom: '4px' }}>{escapeXml(bullet)}</li>
                                                ))}
                                            </ul>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {education && education.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ color: '#1e1f3b', fontSize: '12px', fontWeight: 'bold', letterSpacing: '1px', borderBottom: '2px solid #e8723f', paddingBottom: '4px', marginBottom: '15px' }}>
                                EDUCATION
                            </div>
                            {education.map((edu: any, idx: number) => (
                                <div key={idx} style={{ marginBottom: '15px' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '13px', color: '#1e1f3b' }}>
                                        <span>{escapeXml(edu.degree)}</span>
                                        <span style={{ color: '#999', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(edu.startDate)} – {escapeXml(edu.endDate)}</span>
                                    </div>
                                    <div style={{ color: '#777', fontSize: '12px' }}>{escapeXml(edu.institution)}</div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </foreignObject>
        </svg>
    );

    const renderTemplate3 = () => (
        <svg width="794" height="1123" viewBox="0 0 794 1123" xmlns="http://www.w3.org/2000/svg" fontFamily="Georgia, 'Times New Roman', serif">
            <rect width="794" height="1123" fill="#ffffff"/>
            <rect x="510" width="284" height="1123" fill="#f9f9f9"/>
            <line x1="510" y1="0" x2="510" y2="1123" stroke="#e0e0e0" strokeWidth="1"/>

            {/* Left Column */}
            <foreignObject x="36" y="40" width="458" height="1000">
                <div xmlns="http://www.w3.org/1999/xhtml">
                    <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#1a1a1a', marginBottom: '5px' }}>
                        {escapeXml(personalInfo?.name || '')}
                    </div>
                    <div style={{ fontSize: '11px', color: '#888888', fontFamily: 'Arial, sans-serif', letterSpacing: '1.5px', marginBottom: '15px', textTransform: 'uppercase' }}>
                        {escapeXml(personalInfo?.headline || '')}
                    </div>
                    <div style={{ height: '1px', backgroundColor: '#e0e0e0', marginBottom: '25px' }}></div>

                    {professionalSummary && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ fontSize: '11px', fontWeight: 'bold', fontFamily: 'Arial, sans-serif', letterSpacing: '2px', borderBottom: '0.75px solid #1a1a1a', paddingBottom: '4px', marginBottom: '10px' }}>
                                SUMMARY
                            </div>
                            <div style={{ fontSize: '13px', color: '#444', lineHeight: '1.5' }}>
                                {escapeXml(professionalSummary)}
                            </div>
                        </div>
                    )}

                    {experience && experience.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ fontSize: '11px', fontWeight: 'bold', fontFamily: 'Arial, sans-serif', letterSpacing: '2px', borderBottom: '0.75px solid #1a1a1a', paddingBottom: '4px', marginBottom: '15px' }}>
                                EXPERIENCE
                            </div>
                            {experience.map((exp: any, idx: number) => (
                                <div key={idx} style={{ marginBottom: '20px' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '14px', color: '#1a1a1a', fontFamily: 'Arial, sans-serif' }}>
                                        <span>{escapeXml(exp.jobTitle)}</span>
                                        <span style={{ color: '#999', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(exp.startDate)} – {escapeXml(exp.endDate)}</span>
                                    </div>
                                    <div style={{ color: '#666', fontSize: '13px', fontStyle: 'italic', marginBottom: '5px' }}>
                                        {escapeXml(exp.company)}{exp.location ? `, ${escapeXml(exp.location)}` : ''}
                                    </div>
                                    {exp.bullets && exp.bullets.length > 0 && (
                                        <ul style={{ margin: 0, paddingLeft: '15px', color: '#555', fontSize: '13px', lineHeight: '1.4' }}>
                                            {exp.bullets.map((bullet: string, bIdx: number) => (
                                                <li key={bIdx} style={{ marginBottom: '4px' }}>{escapeXml(bullet)}</li>
                                            ))}
                                        </ul>
                                    )}
                                </div>
                            ))}
                        </div>
                    )}

                    {projects && projects.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ fontSize: '11px', fontWeight: 'bold', fontFamily: 'Arial, sans-serif', letterSpacing: '2px', borderBottom: '0.75px solid #1a1a1a', paddingBottom: '4px', marginBottom: '15px' }}>
                                PROJECTS
                            </div>
                            {projects.map((proj: any, idx: number) => (
                                <div key={idx} style={{ marginBottom: '20px' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '14px', color: '#1a1a1a', fontFamily: 'Arial, sans-serif' }}>
                                        <span>{escapeXml(proj.name)}</span>
                                        <span style={{ color: '#999', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(proj.startDate)} – {escapeXml(proj.endDate)}</span>
                                    </div>
                                    {proj.role && <div style={{ color: '#666', fontSize: '13px', fontStyle: 'italic', marginBottom: '5px' }}>{escapeXml(proj.role)}</div>}
                                    {proj.bullets && proj.bullets.length > 0 && (
                                        <ul style={{ margin: 0, paddingLeft: '15px', color: '#555', fontSize: '13px', lineHeight: '1.4' }}>
                                            {proj.bullets.map((bullet: string, bIdx: number) => (
                                                <li key={bIdx} style={{ marginBottom: '4px' }}>{escapeXml(bullet)}</li>
                                            ))}
                                        </ul>
                                    )}
                                </div>
                            ))}
                        </div>
                    )}

                     {education && education.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ fontSize: '11px', fontWeight: 'bold', fontFamily: 'Arial, sans-serif', letterSpacing: '2px', borderBottom: '0.75px solid #1a1a1a', paddingBottom: '4px', marginBottom: '15px' }}>
                                EDUCATION
                            </div>
                            {education.map((edu: any, idx: number) => (
                                <div key={idx} style={{ marginBottom: '12px' }}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '14px', color: '#1a1a1a', fontFamily: 'Arial, sans-serif' }}>
                                        <span>{escapeXml(edu.degree)}</span>
                                        <span style={{ color: '#999', fontWeight: 'normal', fontSize: '12px' }}>{escapeXml(edu.startDate)} – {escapeXml(edu.endDate)}</span>
                                    </div>
                                    <div style={{ color: '#666', fontSize: '13px', fontStyle: 'italic', marginBottom: '5px' }}>
                                        {escapeXml(edu.institution)}{edu.location ? `, ${escapeXml(edu.location)}` : ''}
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </foreignObject>

            {/* Right Column */}
            <foreignObject x="526" y="40" width="248" height="1000">
                <div xmlns="http://www.w3.org/1999/xhtml" style={{ fontFamily: 'Arial, sans-serif' }}>
                    <div style={{ fontSize: '12px', color: '#555', lineHeight: '1.8', marginBottom: '25px' }}>
                        {personalInfo?.phoneNumber && <div>📞 {escapeXml(personalInfo.phoneNumber)}</div>}
                        {personalInfo?.email && <div>✉️ {escapeXml(personalInfo.email)}</div>}
                        {personalInfo?.linkedin && <div>🔗 {escapeXml(personalInfo.linkedin.replace(/^https?:\/\/(www\.)?/, ''))}</div>}
                        {personalInfo?.github && <div>💻 {escapeXml(personalInfo.github.replace(/^https?:\/\/(www\.)?/, ''))}</div>}
                        {personalInfo?.location && <div>📍 {escapeXml(personalInfo.location)}</div>}
                    </div>

                    <div style={{ height: '1px', backgroundColor: '#e0e0e0', marginBottom: '25px' }}></div>

                    {skills && skills.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ fontSize: '11px', fontWeight: 'bold', color: '#1a1a1a', letterSpacing: '1.5px', borderBottom: '0.75px solid #1a1a1a', paddingBottom: '4px', marginBottom: '10px' }}>
                                HARD SKILLS
                            </div>
                            <div style={{ fontSize: '12px', color: '#555', columnCount: 2, columnGap: '10px' }}>
                                {skills.map((skill: string, idx: number) => (
                                    <div key={idx} style={{ marginBottom: '6px' }}>• {escapeXml(skill)}</div>
                                ))}
                            </div>
                        </div>
                    )}

                    {softSkills && softSkills.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ fontSize: '11px', fontWeight: 'bold', color: '#1a1a1a', letterSpacing: '1.5px', borderBottom: '0.75px solid #1a1a1a', paddingBottom: '4px', marginBottom: '10px' }}>
                                SOFT SKILLS
                            </div>
                            <div style={{ fontSize: '12px', color: '#555', columnCount: 2, columnGap: '10px' }}>
                                {softSkills.map((skill: string, idx: number) => (
                                    <div key={idx} style={{ marginBottom: '6px' }}>• {escapeXml(skill)}</div>
                                ))}
                            </div>
                        </div>
                    )}

                    {certifications && certifications.length > 0 && (
                        <div style={{ marginBottom: '25px' }}>
                            <div style={{ fontSize: '11px', fontWeight: 'bold', color: '#1a1a1a', letterSpacing: '1.5px', borderBottom: '0.75px solid #1a1a1a', paddingBottom: '4px', marginBottom: '10px' }}>
                                CERTIFICATIONS
                            </div>
                            {certifications.map((cert: string, idx: number) => (
                                <div key={idx} style={{ marginBottom: '12px' }}>
                                    <div style={{ fontWeight: 'bold', fontSize: '12px', color: '#555' }}>• {escapeXml(cert)}</div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </foreignObject>
        </svg>
    );

    return (
        <div className="w-full h-full bg-white shadow-lg overflow-y-auto flex justify-center">
            {templateId === 'template1' && renderTemplate1()}
            {templateId === 'template2' && renderTemplate2()}
            {templateId === 'template3' && renderTemplate3()}
        </div>
    );
};

export default LivePreview;